from pydantic import BaseModel, Field
from typing import Literal, Optional, List
class StartCaseRequest(BaseModel):
    title: str
    caseType: Literal["tenancy_deposit", "consumer_ecommerce", "freelance_unpaid"] = "tenancy_deposit"
    description: Optional[str] = None
    amount: Optional[float] = None
    incidentDate: Optional[str] = None
    floorPrice: Optional[float] = None
    mode: Literal["ai", "pvp"] = "ai"
    createdBy: Optional[str] = None

class StartCaseResponse(BaseModel):
    caseId: str

class CaseEvidenceRequest(BaseModel):
    fileType: Literal["text","image", "pdf","audio"]
    storageUrl: str
    text: Optional[str] = None

class CaseEvidenceResponse(BaseModel):
    evidenceId: str

class RunCaseRequest(BaseModel):
    mode: Literal["mvp", "full"]

class RunCaseResponse(BaseModel):
    status: Literal["running"]

class GetCaseResultResponse(BaseModel):
    status: Literal["running", "done", "error","created"]
    settlement: Optional[dict] = None


class Citation(BaseModel):
    """Legal citation model for settlement references."""
    law: str = Field(..., example="Contracts Act 1950")
    section: str = Field(..., example="75")
    excerpt: str = Field(..., description="Relevant excerpt from the law")


class Settlement(BaseModel):
    summary: str = Field(..., description="Summary of the settlement agreement")
    recommended_settlement_rm: float = Field(..., description="Recommended settlement amount in RM")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score of the settlement (0-1)")
    citations: List[Citation] = Field(
        default=[],
        description="Legal citations supporting the settlement"
    )
    # NEW Phase 2: Negotiation metadata
    final_round: Optional[int] = Field(
        default=None,
        description="Round number where settlement was reached"
    )
    
    plaintiff_final_offer: Optional[int] = Field(
        default=None,
        description="Plaintiff's final offer in RM"
    )
    
    defendant_final_offer: Optional[int] = Field(
        default=None,
        description="Defendant's final offer in RM"
    )

# -----------------------------------------------------------------------------
# NEW: Strategic Chips (M1's Commander Console)
# -----------------------------------------------------------------------------
class ChipOption(BaseModel):
    """Single chip option for user selection."""
    label: str = Field(..., description="Display text for the chip button")
    strategy_id: Optional[str] = Field(
        default=None,
        description="Identifier for the underlying strategy this chip triggers (for analytics and backend logic)"
    )
class ChipOptions(BaseModel):
    """
    Model for strategic chip suggestions.
    Generated by M1's chips.py module.
    """
    question: str = Field(
        ...,
        description="Context question for the chips",
        example="The landlord claims damages worth RM500. How do you respond?"
    )
    
    options: List[ChipOption] = Field(
        ...,
        min_items=2,
        max_items=4,
        description="2-4 strategic options for user"
    )
# --------------------------------------------------------
#phase 2 - turn-based negotiation
# --------------------------------------------------------
class TurnRequest(BaseModel):
    """
    Request model for /next-turn endpoint.
    Handles user strategic directive and evidence injection during negotiation.
    """
    caseId: str = Field(..., description="case ID from phase1.")
    user_message: str = Field(default="", description="Optional strategic directive to guide the plaintiff AI agent.")
    evidence_uris: Optional[list[str]] = Field(default=[], description="Array of Gemini File API URIs for newly uploaded evidence.")
    # user's floor price (hidden from opponent, used for negotiation strategy)
    floor_price: Optional[float] = Field(default=None, description="User's minimum acceptable settlement amount in RM")


class PvpTurnRequest(BaseModel):
    """
    Request model for /pvp-turn endpoint.
    Handles one side's turn in a PvP negotiation.
    """
    caseId: str = Field(..., description="Case ID.")
    user_message: str = Field(default="", description="Strategic directive from the human commander.")
    user_role: Literal["plaintiff", "defendant"] = Field(..., description="The role of the user sending this turn.")
    userId: Optional[str] = Field(default=None, description="Firebase Auth UID of the user.")
    evidence_uris: Optional[list[str]] = Field(default=[], description="Array of Gemini File API URIs.")
    floor_price: Optional[float] = Field(default=None, description="User's floor/ceiling price in RM.")


class JoinCaseRequest(BaseModel):
    """
    Request model for /join endpoint.
    Defendant joins a PvP case via invite link.
    """
    userId: str = Field(..., description="Firebase Auth UID of the joining user.")
    role: Literal["defendant"] = Field(default="defendant", description="Role to join as.")
    isAnonymous: bool = Field(default=True, description="Whether user is signed in anonymously.")
    displayName: Optional[str] = Field(default=None, description="User display name if available.")


class DefendantRespondRequest(BaseModel):
    """
    Request model for defendant onboarding — defendant reviews case and provides their side.
    """
    userId: str = Field(..., description="Firebase Auth UID of the defendant.")
    defendantDescription: str = Field(default="", description="Defendant's side of the story.")
    defendantCeilingPrice: Optional[float] = Field(default=None, description="Max amount defendant is willing to pay (hidden from plaintiff).")
    defendantStartingOffer: Optional[float] = Field(default=None, description="Defendant's opening offer in RM.")
    isAnonymous: bool = Field(default=True, description="Whether user is signed in anonymously.")
    displayName: Optional[str] = Field(default=None, description="User display name if available.")


class UpdateParticipantRequest(BaseModel):
    """
    Request model for updating a participant's UID after auth upgrade.
    """
    oldUserId: str = Field(..., description="Previous (anonymous) UID.")
    newUserId: str = Field(..., description="New (Google) UID.")
    role: Literal["plaintiff", "defendant"] = Field(..., description="Role to update.")
    displayName: Optional[str] = Field(default=None, description="User display name.")

class TurnResponse(BaseModel):
    """
    Response model for /next-turn endpoint.
    Contains AI response, audio, auditor feedback, and strategic chips.
    """
    agent_message: str = Field(..., description="AI defendant's (opponent) message.")
    plaintiff_message: Optional[str] = Field(default=None, description="AI plaintiff's (your agent) message.")
    current_round: int = Field(default=1, description="Authoritative round number from backend.")
    #audio playback
    audio_url: Optional[str] = Field(default=None, description="firebase storage URI for TTS audio of agent_message.")
    #auditor feedback (M2's validation)
    auditor_warning: Optional[str] = Field(default=None, description="warning message if auditor detects citation issues")
    auditor_passed: bool = Field(default=True, description="whether the passed the auditor check")
    
    #strategic chips (connect with M1)
    chips: Optional[ChipOptions] = Field(
        default=None, 
        description="commander's console chip options for user", 
        json_schema_extra={
            "example": {
                "question": "The landlord claims damages...",
                "options": [
                    {"label": "Demand proof"},
                    {"label": "Cite Wear & Tear"},
                    {"label": "Offer Split"}
                    ]
                }
            }
        )
    game_state: str = Field(default="active", description="current negotiation state: 'active', 'settled', 'failed', 'pending_decision', 'deadlock'")
    counter_offer_rm: Optional[float] = Field(default=None, description="AI's counter offer amount in RM")

#NEW: Evidence Validation (M2's Gemini Vision)
# -----------------------------------------------------------------------------
class ValidateEvidenceRequest(BaseModel):
    """
    Request model for /validate-evidence endpoint.
    Uploads and validates evidence using Gemini Vision.
    """
    image_url: str = Field(..., description="Firebase Storage URL of uploaded file")
    user_claim: str = Field(
        ...,
        description="User's claim about what the evidence shows",
        example="This photo shows damage to the wall"
    )
    mime_type: str = Field(
        ...,
        description="MIME type of the file",
        example="image/jpeg"
    )

class ValidateEvidenceResponse(BaseModel):
    """
    Response model for /validate-evidence endpoint.
    Returns validation results and Gemini File API URI.
    """
    is_relevant: bool = Field(..., description="Whether the evidence is valid and relevant")
    summary_for_agent: Optional[str] = Field(
        ...,
        description="M2's Gemini Vision summary to inject into M1's prompts",
        example="The image is blurry and does not clearly show the claimed damage."
    )
    confidence_score: Optional[float] = Field(
        ...,
        ge = 0.0,
        le = 1.0,
        description="Confidence score of validation (0.0 to 1.0)"
    )
    file_uri: Optional[str] = Field(
        default=None,
        description="Gemini File API URI of the validated evidence",
        example="gemini://file/abc123"
    )
# auditor response (M2's citation validator)
# -----------------------------------------------------------------------------
class AuditorResponse(BaseModel):
    """
    Internal model for auditor validation result.
    Used by M2's auditor.py module.
    """
    passed: bool = Field(..., description="Whether the response passed validation")
    
    warning_message: Optional[str] = Field(
        default=None,
        description="Warning if validation failed",
        example="Citation Mismatch: Section 15 refers to 'implied condition', not 'refunds'."
    )
    
    # NEW Phase 2: Retry suggestion
    retry_count: int = Field(
        default=0,
        description="Number of times this response has been retried"
    )



# court Filing Export (Sad Path)
# -----------------------------------------------------------------------------
class CourtFilingRequest(BaseModel):
    """
    Request model for /export-pdf endpoint.
    Generates Form 198 (Small Claims Court) JSON.
    """
    caseId: str = Field(..., description="The case ID")


class CourtFilingResponse(BaseModel):
    """
    Response model for /export-pdf endpoint.
    Returns structured JSON for frontend to render as printable HTML.
    """
    plaintiff_details: str = Field(
        ...,
        description="Plaintiff information",
        example="Name: John Doe, ID: 123456-78-9012"
    )
    
    defendant_details: str = Field(
        ...,
        description="Defendant information",
        example="Name: ABC Property Management, Reg No: 202301234567"
    )
    
    statement_of_claim: str = Field(
        ...,
        description="Formal statement of claim text"
    )
    
    amount_claimed: str = Field(
        ...,
        description="Amount being claimed",
        example="RM 2,500"
    )
    
    facts_list: List[str] = Field(
        ...,
        description="List of facts supporting the claim"
    )
    
    # NEW Phase 2: Negotiation summary
    negotiation_summary: Optional[str] = Field(
        default=None,
        description="Summary of failed negotiation attempts"
    )

# Game State Tracking (Internal Use)
# =============================================================================
class GameState(BaseModel):
    """
    Internal model for tracking negotiation state.
    Used by M3's orchestrator.py.
    """
    status: Literal["active", "settled", "deadlock", "pending_decision"] = Field(
        ...,
        description="Current game status"
    )
    
    current_round: int = Field(..., ge=1, le=5, description="Current round (1-4.5)")
    
    plaintiff_offer: Optional[int] = Field(default=None)
    defendant_offer: Optional[int] = Field(default=None)
    
    floor_price_met: bool = Field(
        default=False,
        description="Whether defendant offer meets user's floor price"
    )
    
    auditor_retry_count: int = Field(
        default=0,
        description="Number of auditor retries for current turn"
    )


# =============================================================================
# Helper Models
# =============================================================================

class ErrorResponse(BaseModel):
    """Standard error response model."""
    error: str = Field(..., description="Error message")
    detail: Optional[str] = Field(default=None, description="Additional error details")
    code: Optional[str] = Field(default=None, description="Error code")